Repository googleapis/python-storage-transfer, pull requests merged in 2021-08, with the labels that each got.

#9 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: automerge, cla: yes, samples, api: storagetransfer

#13 chore: migrate to main branch
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  owlbot.py
Labels: cla: yes, api: storagetransfer

#6 feat: bump release level to production/stable
  .repo-metadata.json
  docs/README.rst
  setup.py
Labels: automerge, cla: yes, api: storagetransfer
